name: Python application workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cd .. # go to the parent directory
          python -m modular_flask.loyalty_app &
          PID=$!
          sleep 3
          if ! kill -0 $PID; then
            echo "Flask app failed to start"
            exit 1
          fi
          kill $PID
